/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.gob.mef.sisevent.web.utils;

import java.util.StringTokenizer;

/**
 *
 * @author cafach
 */
public class ConvertirLista extends javax.swing.JFrame {

     /**
	 * 
	 */
	private static final long serialVersionUID = -7595505101818802383L;
	public static final String NEWLINE = System.getProperty("line.separator");
     public static final String EOL = NEWLINE;
         
    /**
     * Creates new form ConvertirLista
     */
    public ConvertirLista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        variablesLista = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoDeCambio = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        textoCambiado = new javax.swing.JTextArea();
        getAndSet = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        variablesLista.setColumns(20);
        variablesLista.setRows(5);
        jScrollPane1.setViewportView(variablesLista);

        textoDeCambio.setColumns(20);
        textoDeCambio.setRows(5);
        jScrollPane2.setViewportView(textoDeCambio);

        textoCambiado.setColumns(20);
        textoCambiado.setRows(5);
        jScrollPane3.setViewportView(textoCambiado);

        getAndSet.setText("Considerar Get Y Set");

        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("<html><pre>**  OR  **=$$\n\n**   Dato Exacto\n*A*  Primera en mayuscula, el resto como esta;\n*AA* Todo mayuscula;\n*a*  Primera en minuscula, el resto como esta;\n*aa* Todo en minuscula;\n\n$$   Dato Exacto\n$A$  Primera en mayuscula, el resto como esta;\n$AA$ Todo mayuscula;\n$a$  Primera en minuscula, el resto como esta;\n$aa$ Todo en minuscula;\n</pre></html>"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(getAndSet)
                            .addComponent(jButton1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(getAndSet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String s = variablesLista.getText();
        String ss = textoDeCambio.getText();
        if (s != null) {
            StringTokenizer st = new StringTokenizer(s, EOL);
            StringBuffer sb = new StringBuffer();
            int countador = 0;
            while (st.hasMoreElements()) {
                String sdato = st.nextToken();
                countador++;
                System.out.println(sdato + " " + countador);
                if (sdato.length() > 0) {
                    String dato = "";
                    if (sdato.endsWith("\r")) {
                        dato = sdato.replace("\r", "");
                    } else {
                        dato = sdato;
                    }
                    
                    if (dato.contains("=")) {
                        StringTokenizer st2 = new StringTokenizer(dato, "=");
                        String dato1 = st2.nextToken();
                        String dato2 = st2.nextToken();
                        String sr = ss.replace("**", dato1);
                        
                        sr = sr.replace("*A*", dato1.substring(0,1).toUpperCase()+ dato1.substring(1));
                        sr = sr.replace("*AA*", dato1.toUpperCase());
                        sr = sr.replace("*a*", dato1.substring(0,1).toLowerCase()+ dato1.substring(1));
                        sr = sr.replace("*aa*", dato1.toLowerCase());
                        
                        sr = sr.replace("$$", dato2);
                        
                        sr = sr.replace("$A$", dato2.substring(0,1).toUpperCase()+ dato2.substring(1));
                        sr = sr.replace("$AA$", dato2.toUpperCase());
                        sr = sr.replace("$a$", dato2.substring(0,1).toLowerCase()+ dato2.substring(1));
                        sr = sr.replace("$aa$", dato2.toLowerCase());
                        
                        sb.append(sr).append(EOL);
                    } else {
                        String sr = ss.replace("**", dato);                        
                        sr = sr.replace("*A*", dato.substring(0,1).toUpperCase()+ dato.substring(1));
                        sr = sr.replace("*AA*", dato.toUpperCase());
                        sr = sr.replace("*a*", dato.substring(0,1).toLowerCase()+ dato.substring(1));
                        sr = sr.replace("*aa*", dato.toLowerCase());
                        
                        sb.append(sr).append(EOL);
                    }
                    
                }

					    //////CONVERSION
                //sb.append("doc.add(new Field(\"").append(dato).append("\", ").append(dato).append(", Field.Store.NO,Field.Index.ANALYZED));").append('\n');
                //sb.append("String ").append(dato).append(" = (rcvCvIdentificacionVISTADto.get").append(dato.substring(0, 1).toUpperCase()).append(dato.substring(1)).append("() == null ? \"\": rcvCvIdentificacionVISTADto.get").append(dato.substring(0, 1).toUpperCase()).append(dato.substring(1)).append("());").append('\n');
                ////////////////
            }
            String retorno = sb.toString();
            if (getAndSet.isSelected()) {
                retorno = alanizarGetAnSet(sb.toString(), 0);
            }
            textoCambiado.setText(retorno);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    public String alanizarGetAnSet(String s, int inipost) {
        StringBuffer sb = new StringBuffer();
        StringTokenizer sz = new StringTokenizer(s, " ", true);
        while (sz.hasMoreElements()) {
            String dato = sz.nextToken();
            int posget = dato.indexOf("get", inipost);
            int posset = dato.indexOf("set", inipost);
            int posis = dato.indexOf("is", inipost);
            if (posget > -1 && dato.length() > (posget + 4)) {
                String dato1 = dato.substring(0, (posget + 3));
                String dato2 = dato.substring((posget + 3), (posget + 4)).toUpperCase();
                String dato3 = dato.substring((posget + 4));
                dato = dato1 + dato2 + dato3;

                int nuevapos = dato.indexOf("get", (posget + 4));
                //dato = dato.substring(0,(posget+3))+dato.substring((posget+3),1).toUpperCase()+dato.substring((posget+4));
                if (nuevapos > -1) {
                    dato = alanizarGetAnSet(dato, nuevapos);
                }
            }
            if (posset > -1 && dato.length() > (posset + 4)) {
                String dato1 = dato.substring(0, (posset + 3));
                String dato2 = dato.substring((posset + 3), (posset + 4)).toUpperCase();
                String dato3 = dato.substring((posset + 4));
                dato = dato1 + dato2 + dato3;
                int nuevapos = dato.indexOf("set", (posset + 4));
                //dato = dato.substring(0,(posset+3))+dato.substring((posset+3),1).toUpperCase()+dato.substring((posset+4));
                if (nuevapos > -1) {
                    dato = alanizarGetAnSet(dato, nuevapos);
                }
            }
            if (posis > -1 && dato.length() > (posis + 3)) {
                String dato1 = dato.substring(0, (posis + 2));
                String dato2 = dato.substring((posis + 2), (posis + 3)).toUpperCase();
                String dato3 = dato.substring((posis + 3));
                dato = dato1 + dato2 + dato3;
                int nuevapos = dato.indexOf("is", (posis + 3));
                //dato = dato.substring(0,(posis+2))+dato.substring((posis+2),1).toUpperCase()+dato.substring((posis+3));
                if (nuevapos > -1) {
                    dato = alanizarGetAnSet(dato, nuevapos);
                }
            }
            sb.append(dato);
        }

        return sb.toString();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConvertirLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConvertirLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConvertirLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConvertirLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConvertirLista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox getAndSet;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea textoCambiado;
    private javax.swing.JTextArea textoDeCambio;
    private javax.swing.JTextArea variablesLista;
    // End of variables declaration//GEN-END:variables
}
