CREATE TABLE SISEVENT.MS_USUARIOS 
   (	
    IDUSUARIO NUMBER(10,0) NOT NULL ENABLE, 
	USERNAME VARCHAR2(50) NOT NULL ENABLE, 
	NOMBRES VARCHAR2(100) NOT NULL ENABLE, 
	APELLIDO_PATERNO VARCHAR2(100) NOT NULL ENABLE, 
	APELLIDO_MATERNO VARCHAR2(100), 
	CONTRASENIA VARCHAR2(50) NOT NULL ENABLE, 
    SEDE VARCHAR2(150), 
	IDUNIDAD NUMBER(10,0) NOT NULL ENABLE, 
	ANEXO VARCHAR2(20), 
	CELULAR VARCHAR2(20), 
	CORREO VARCHAR2(200),
	IDUSER_CREA NUMBER(10,0) NOT NULL ENABLE, 
	IDUSER_MODIF NUMBER(10,0) NOT NULL ENABLE, 
	FECHA_CREA DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	FECHA_MODIF DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	RTMADDRESS VARCHAR2(50) NOT NULL ENABLE, 
	RTMADDRESSMODIF VARCHAR2(50) NOT NULL ENABLE, 
	ESTADO NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE	
    );
 

   COMMENT ON COLUMN SISEVENT.MS_USUARIOS.IDUSUARIO IS 'Código de usuario, ID';
 
   COMMENT ON COLUMN SISEVENT.MS_USUARIOS.USERNAME IS 'Nombre corto, NOMBRE CORTO, TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_USUARIOS.NOMBRES IS 'Nombres, NOMBRES, TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_USUARIOS.APELLIDO_PATERNO IS 'Apellido paterno del usuario, APELLIDO PATERNO, TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_USUARIOS.APELLIDO_MATERNO IS 'Apellido materno del usuario, APELLIDO MATERNO, TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_USUARIOS.CONTRASENIA IS 'Contraseña del usuario, CONTRASEÑA, PASSWORD';
 
   COMMENT ON COLUMN SISEVENT.MS_USUARIOS.IDUSER_CREA IS 'Usuario que crea, USUARIO QUE CREA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_USUARIOS.IDUSER_MODIF IS 'Usuario que modifica, USUARIO QUE MODIFICA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_USUARIOS.FECHA_CREA IS 'Fecha de creación, FECHA DE CREACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_USUARIOS.FECHA_MODIF IS 'Fecha de modificación, FECHA DE MODIFICACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_USUARIOS.RTMADDRESS IS 'Dirección de red del que crea, DIRECCIÓN DE RED DEL CREADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_USUARIOS.RTMADDRESSMODIF IS 'Dirección de red del que modifica, DIRECCIÓN DE RED DEL MODIFICADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_USUARIOS.ESTADO IS 'Estado del usuario, ESTADO';
 
   COMMENT ON COLUMN SISEVENT.MS_USUARIOS.SEDE IS 'Sede en la que trabaja, SEDE EN LA QUE TRABAJA, SELECT, IDPARAMETRO';
 
   COMMENT ON COLUMN SISEVENT.MS_USUARIOS.IDUNIDAD IS 'Código de la unidad orgánica, UO A LA QUE PERTENECE, SELECT, IDUNIDAD';
 
   COMMENT ON COLUMN SISEVENT.MS_USUARIOS.ANEXO IS 'Anexo, ANEXO, TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_USUARIOS.CELULAR IS 'Celular, CELULAR, TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_USUARIOS.CORREO IS 'Correo, CORREO, TEXT';
 
   COMMENT ON TABLE SISEVENT.MS_USUARIOS  IS 'ALMACENA LOS USUARIOS REGISTRADOS EN EL SISTEMA USUARIOS, DEL, USUARIO';
 

CREATE TABLE SISEVENT.MS_ROLES 
   (	
    IDROL NUMBER(10,0) NOT NULL ENABLE, 
	USERNAME VARCHAR2(50) NOT NULL ENABLE, 
	ROL VARCHAR2(100) NOT NULL ENABLE, 
	IDUSER_CREA NUMBER(10,0) NOT NULL ENABLE, 
	IDUSER_MODIF NUMBER(10,0) NOT NULL ENABLE, 
	FECHA_CREA DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	FECHA_MODIF DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	RTMADDRESS VARCHAR2(50) NOT NULL ENABLE, 
	RTMADDRESSMODIF VARCHAR2(50) NOT NULL ENABLE, 
	ESTADO NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE
    );
 

   COMMENT ON COLUMN SISEVENT.MS_ROLES.IDROL IS 'Código del rol, ID';
 
   COMMENT ON COLUMN SISEVENT.MS_ROLES.USERNAME IS 'Nombre corto del usuario, NOMBRE CORTO';
 
   COMMENT ON COLUMN SISEVENT.MS_ROLES.ROL IS 'Nombre del Rol que se está asignado, ROL, SELECT';
 
   COMMENT ON COLUMN SISEVENT.MS_ROLES.IDUSER_CREA IS 'Usuario que crea, USUARIO QUE CREA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_ROLES.IDUSER_MODIF IS 'Usuario que modifica, USUARIO QUE MODIFICA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_ROLES.FECHA_CREA IS 'Fecha de creación, FECHA DE CREACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_ROLES.FECHA_MODIF IS 'Fecha de modificación, FECHA DE MODIFICACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_ROLES.RTMADDRESS IS 'Dirección de red del que crea, DIRECCIÓN DE RED DEL CREADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_ROLES.RTMADDRESSMODIF IS 'Dirección de red del que modifica, DIRECCIÓN DE RED DEL MODIFICADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_ROLES.ESTADO IS 'Estado del rol, ESTADO';
 
   COMMENT ON TABLE SISEVENT.MS_ROLES  IS 'ROLES DEL SISTEMA, ROLES';
 

  
 CREATE TABLE SISEVENT.MS_UNIDADES_ORG 
   (	
    IDUNIDAD NUMBER(10,0) NOT NULL ENABLE, 
	IDPADRE NUMBER(10,0) DEFAULT null, 
	CODIGO VARCHAR2(60), 
	DESCRIPCION VARCHAR2(255) NOT NULL ENABLE, 
	ACRONIMO VARCHAR2(25), 
	FLAGOFGENERAL NUMBER(1,0), 
	IDUSER_CREA NUMBER(10,0) NOT NULL ENABLE,
    IDUSER_MODIF NUMBER(10,0) NOT NULL ENABLE,
	FECHA_CREA DATE DEFAULT SYSDATE NOT NULL ENABLE,	 
	FECHA_MODIF DATE DEFAULT SYSDATE NOT NULL ENABLE,  
	RMTADDRESS VARCHAR2(50) NOT NULL ENABLE, 
	RMTADDRESSRST VARCHAR2(50) NOT NULL ENABLE,
    ESTADO NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE
    );

   COMMENT ON COLUMN SISEVENT.MS_UNIDADES_ORG.IDUNIDAD IS 'Código de la unidad orgánica, ID';
 
   COMMENT ON COLUMN SISEVENT.MS_UNIDADES_ORG.IDPADRE IS 'Unidad orgánica de la que depende, DEPENDENCIA, DIALOG, IDUNIDAD';
 
   COMMENT ON COLUMN SISEVENT.MS_UNIDADES_ORG.CODIGO IS 'Código documental de la unidad orgánica, CÓDIGO, TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_UNIDADES_ORG.DESCRIPCION IS 'Nombre de la Unidad Orgánica, Nombre, TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_UNIDADES_ORG.ACRONIMO IS 'Acrónimo de la Unidad Orgánica, Acrónimo, TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_UNIDADES_ORG.FLAGOFGENERAL IS 'Determina si  se trata de una Oficina General, ES OFICINA GENERAL, CHECKBOX ';
 
   COMMENT ON COLUMN SISEVENT.MS_UNIDADES_ORG.IDUSER_CREA IS 'Usuario que crea, USUARIO QUE CREA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_UNIDADES_ORG.FECHA_CREA IS 'Fecha de cración, FECHA DE CREACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_UNIDADES_ORG.IDUSER_MODIF IS 'Usuario que modifica, USUARIO QUE MODIFICA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_UNIDADES_ORG.FECHA_MODIF IS 'Fecha de modificación, FECHA DE MODIFICACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_UNIDADES_ORG.ESTADO IS 'Estado de la Unidad Orgánica, ESTADO';
 
   COMMENT ON COLUMN SISEVENT.MS_UNIDADES_ORG.RMTADDRESS IS 'Dirección de red del que crea, DIRECCIÓN DE RED DEL CREADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_UNIDADES_ORG.RMTADDRESSRST IS 'Dirección de red del que modifica, DIRECCIÓN DE RED DEL MODIFICADOR, SISTEMA';
 
   COMMENT ON TABLE SISEVENT.MS_UNIDADES_ORG  IS 'UNIDADES ORGÁNICAS, DE LA ,UNIDAD ORGÁNICA';
 

CREATE TABLE SISEVENT.MS_PAISES 
   (	
    PAI_PK NUMBER(10,0) DEFAULT 1 NOT NULL ENABLE, 
	PAI_ISONUM NUMBER(10,0) DEFAULT 1, 
	PAI_ISO2 VARCHAR2(5), 
	PAI_ISO3 VARCHAR2(5), 
	PAI_NOMBRE VARCHAR2(100) NOT NULL ENABLE, 
	FECHA_CREA DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	FECHA_MODIF DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	IDUSER_CREA NUMBER(10,0) DEFAULT 1 NOT NULL ENABLE, 
	IDUSER_MODIF NUMBER(10,0) DEFAULT 1 NOT NULL ENABLE,	 
	RMTADDRESS VARCHAR2(50) NOT NULL ENABLE, 
	RMTADDRESSRST VARCHAR2(50) NOT NULL ENABLE,
    ESTADO NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE
    ); 
  
  CREATE TABLE SISEVENT.MS_UBIGEO 
   (	
    CODDPTO NUMBER(2,0) DEFAULT null NOT NULL ENABLE, 
	CODPROV NUMBER(2,0) DEFAULT null NOT NULL ENABLE, 
	CODDIST NUMBER(2,0) DEFAULT null NOT NULL ENABLE, 
	NOMBRE VARCHAR2(100) NOT NULL ENABLE, 
	FECHA_CREA DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	FECHA_MODIF DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	IDUSER_CREA NUMBER(10,0) DEFAULT null NOT NULL ENABLE, 
	IDUSER_MODIF NUMBER(10,0) DEFAULT null NOT NULL ENABLE, 	 
	RMTADDRESS VARCHAR2(50) NOT NULL ENABLE, 
	RMTADDRESSRST VARCHAR2(50) NOT NULL ENABLE,
    ESTADO NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE
    );

   COMMENT ON COLUMN SISEVENT.MS_UBIGEO.CODDPTO IS 'Código del departamento según INEI, CÓDIGO DEPARTAMENTO';
 
   COMMENT ON COLUMN SISEVENT.MS_UBIGEO.CODPROV IS 'Código de provincia según INEI, CÓDIGO PROVINCIA';
 
   COMMENT ON COLUMN SISEVENT.MS_UBIGEO.CODDIST IS 'Código de distrito según INEI, CÓDIGO DISTRITO';
 
   COMMENT ON COLUMN SISEVENT.MS_UBIGEO.NOMBRE IS 'Nombre de la Localidad, NOMBRE, TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_UBIGEO.FECHA_CREA IS 'Fecha de creación, FECHA DE CREACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_UBIGEO.FECHA_MODIF IS 'Fecha de modificación, FECHA DE MODIFICACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_UBIGEO.IDUSER_CREA IS 'Usuario que crea, USUARIO QUE CREA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_UBIGEO.IDUSER_MODIF IS 'Usuario que modifica, USUARIO QUE MODIFICA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_UBIGEO.ESTADO IS 'Estado del UBIGEO, ESTADO';
 
   COMMENT ON COLUMN SISEVENT.MS_UBIGEO.RMTADDRESS IS 'Dirección de red del que crea, DIRECCIÓN DE RED DEL CREADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_UBIGEO.RMTADDRESSRST IS 'Dirección de red del que modifica, DIRECCIÓN DE RED DEL MODIFICADOR, SISTEMA';
 
   COMMENT ON TABLE SISEVENT.MS_UBIGEO  IS 'UBIGEO DATOS OTORGADOS POR EL INEI, DEL, UBIGEO';
 
 
CREATE TABLE SISEVENT.PRT_PARAMETROS 
   (	
    IDPARAMETRO NUMBER(10,0) NOT NULL ENABLE, 
	IDPADRE NUMBER(10,0), 
	DESCRIPCION VARCHAR2(150) NOT NULL ENABLE, 
	DESCRIPCIONCORTA VARCHAR2(150), 
	ORDEN NUMBER(10,0), 
	IDUSER_CREA NUMBER(10,0) NOT NULL ENABLE, 
	IDUSER_MODIF NUMBER(10,0) NOT NULL ENABLE, 
	FECHA_CREA DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	FECHA_MODIF DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	RTMADDRESS VARCHAR2(50) NOT NULL ENABLE, 
	RTMADDRESSMODIF VARCHAR2(50) NOT NULL ENABLE, 
	ESTADO NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE
    ); 

   COMMENT ON COLUMN SISEVENT.PRT_PARAMETROS.IDPARAMETRO IS 'Código del parámetro, ID';
 
   COMMENT ON COLUMN SISEVENT.PRT_PARAMETROS.IDPADRE IS 'Código del parámetro padre, PADRE, SELECT,IDPARAMETRO';
 
   COMMENT ON COLUMN SISEVENT.PRT_PARAMETROS.DESCRIPCION IS 'Parámetro, PARÁMETRO, TEXT';
 
   COMMENT ON COLUMN SISEVENT.PRT_PARAMETROS.DESCRIPCIONCORTA IS 'Opción corta, OPCIÓN CORTA, TEXT';
 
   COMMENT ON COLUMN SISEVENT.PRT_PARAMETROS.ORDEN IS 'Orden de presentación, ORDEN, NUMBER';
 
   COMMENT ON COLUMN SISEVENT.PRT_PARAMETROS.IDUSER_CREA IS 'Usuario que crea, USUARIO QUE CREA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.PRT_PARAMETROS.IDUSER_MODIF IS 'Usuario que modifica, USUARIO QUE MODIFICA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.PRT_PARAMETROS.FECHA_CREA IS 'Fecha de creación, FECHA DE CREACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.PRT_PARAMETROS.FECHA_MODIF IS 'Fecha de modificación, FECHA DE MODIFICACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.PRT_PARAMETROS.RTMADDRESS IS 'Dirección de red del que crea, DIRECCIÓN DE RED DEL CREADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.PRT_PARAMETROS.RTMADDRESSMODIF IS 'Dirección de red del que modifica, DIRECCIÓN DE RED DEL MODIFICADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.PRT_PARAMETROS.ESTADO IS 'Estado del paámetro, ESTADO';
 
   COMMENT ON TABLE SISEVENT.PRT_PARAMETROS  IS 'ALMACENA LOS PARÁMETROS REGISTRADOS EN EL SISTEMA PARÁMETROS, DEL PARÁMETRO';
 

CREATE TABLE SISEVENT.MS_INSTITUCIONES 
   (	
    IDPROVEE NUMBER(10,0) NOT NULL ENABLE, 
	RAZON_SOCIAL VARCHAR2(255) NOT NULL ENABLE, 
	SIGLAS VARCHAR2(50), 
	RUC VARCHAR2(20), 
	CORREO VARCHAR2(150), 
	WEB VARCHAR2(150), 
	TELEFONO VARCHAR2(100), 
	FAX VARCHAR2(100), 
	CODPAIS NUMBER(10,0) DEFAULT null, 
	CODDPTO NUMBER(2,0) DEFAULT null, 
	CODPROV NUMBER(2,0) DEFAULT null, 
	CODDIST NUMBER(2,0) DEFAULT null, 
	DIRECCION VARCHAR2(550), 
	FECHA_CREA DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	FECHA_MODIF DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	IDUSER_CREA NUMBER(10,0) DEFAULT null NOT NULL ENABLE, 
	IDUSER_MODIF NUMBER(10,0) DEFAULT null NOT NULL ENABLE, 
	TIPOENTIDAD VARCHAR2(150) DEFAULT 'OTROS', 
	RMTADDRESS VARCHAR2(50) NOT NULL ENABLE, 
	RMTADDRESSRST VARCHAR2(50) NOT NULL ENABLE, 
	ESTADO NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE
    );

   COMMENT ON COLUMN SISEVENT.MS_INSTITUCIONES.IDPROVEE IS 'Código de la Institución o Entidad, ID';
 
   COMMENT ON COLUMN SISEVENT.MS_INSTITUCIONES.RAZON_SOCIAL IS 'Nombre de la Institución o Entidad, NOMBRE, TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_INSTITUCIONES.SIGLAS IS 'Siglas o abreviación distintivo de la Institución o Entidad, SIGLAS, TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_INSTITUCIONES.RUC IS 'Registro Único Del Contribuyente De La Institución O Entidad, RUC, TEXTNUMBER';
 
   COMMENT ON COLUMN SISEVENT.MS_INSTITUCIONES.CORREO IS 'Correo electrónico del representante de la Institución o Entidad, CORREO, TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_INSTITUCIONES.WEB IS 'Pagina Web de la Institución o Entidad, PAGINA WEB, TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_INSTITUCIONES.TELEFONO IS 'Teléfono de la Institución o Entidad, TELÉFONO, TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_INSTITUCIONES.FAX IS 'Fax de la Institución o Entidad, FAX, TEXT ';
 
   COMMENT ON COLUMN SISEVENT.MS_INSTITUCIONES.CODPAIS IS 'Código del país, PAÍS, SELECT, PAI_PK';
 
   COMMENT ON COLUMN SISEVENT.MS_INSTITUCIONES.CODDPTO IS 'Código del departamento según INEI, DEPARTAMENTO, SELECT-P, CODDPTO';
 
   COMMENT ON COLUMN SISEVENT.MS_INSTITUCIONES.CODPROV IS 'Código de provincia según INEI, PROVINCIA, SELECT-M, CODPROV';
 
   COMMENT ON COLUMN SISEVENT.MS_INSTITUCIONES.CODDIST IS 'Código de distrito según INEI, DISTRITO, SELECT-H, CODDIST';
 
   COMMENT ON COLUMN SISEVENT.MS_INSTITUCIONES.DIRECCION IS 'Dirección de la Institución o Entidad, DIRECCIÓN, TEXTAREA';
 
   COMMENT ON COLUMN SISEVENT.MS_INSTITUCIONES.FECHA_CREA IS 'Fecha de creación, FECHA DE CREACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_INSTITUCIONES.FECHA_MODIF IS 'Fecha de modificación, FECHA DE MODIFICACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_INSTITUCIONES.IDUSER_CREA IS 'Usuario que crea, USUARIO QUE CREA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_INSTITUCIONES.IDUSER_MODIF IS 'Usuario que modifica, USUARIO QUE MODIFICA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_INSTITUCIONES.ESTADO IS 'Estado de la institución, ESTADO';
 
   COMMENT ON COLUMN SISEVENT.MS_INSTITUCIONES.RMTADDRESS IS 'Dirección de red del que crea, DIRECCIÓN DE RED DEL CREADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_INSTITUCIONES.RMTADDRESSRST IS 'Dirección de red del que modifica, DIRECCIÓN DE RED DEL MODIFICADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_INSTITUCIONES.TIPOENTIDAD IS 'Tipo de entidad, TIPO DE ENTIDAD, TEXT';
 
   COMMENT ON TABLE SISEVENT.MS_INSTITUCIONES  IS 'INSTITUCIONES Y ENTIDADES, DE LA, INSTITUCION Y/O ENTIDAD';
 
 

CREATE TABLE SISEVENT.MS_PERSONAS 
   (	
    IDPERSON NUMBER(10,0) NOT NULL ENABLE, 
	APELLIDO_PATERNO VARCHAR2(100) NOT NULL ENABLE, 
	APELLIDO_MATERNO VARCHAR2(100), 
	NOMBRES VARCHAR2(150) NOT NULL ENABLE, 
	SEXO VARCHAR2(1) DEFAULT 'M', 
	TIPODOCUMENTO NUMBER(10,0), 
	DOCUMENTO_NUMERO VARCHAR2(25) NOT NULL ENABLE, 
	CORREO VARCHAR2(50), 
	TELEFONO VARCHAR2(15), 
	CELULAR VARCHAR2(15), 
	CODPAIS NUMBER(10,0) DEFAULT null NOT NULL ENABLE, 
	CODDPTO NUMBER(2,0) DEFAULT null NOT NULL DISABLE, 
	CODPROV NUMBER(2,0) DEFAULT null NOT NULL DISABLE, 
	CODDIST NUMBER(2,0) DEFAULT null NOT NULL DISABLE, 
	DIRECCION VARCHAR2(255) NOT NULL DISABLE, 
	TIENEFOTO VARCHAR2(2) DEFAULT 'NO', 
	FECHA_CREA DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	FECHA_MODIF DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	IDUSER_CREA NUMBER(10,0) NOT NULL ENABLE, 
	IDUSER_MODIF NUMBER(10,0) NOT NULL ENABLE, 	 
	RMTADDRESS VARCHAR2(50) NOT NULL ENABLE, 
	RMTADDRESSRST VARCHAR2(50) NOT NULL ENABLE,
    ESTADO NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE
    );

   COMMENT ON COLUMN SISEVENT.MS_PERSONAS.IDPERSON IS 'Código de la persona, ID';
 
   COMMENT ON COLUMN SISEVENT.MS_PERSONAS.APELLIDO_PATERNO IS 'Apellido paterno, APELLIDO PATERNO, TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_PERSONAS.APELLIDO_MATERNO IS 'Apellido materno, APELLIDO MATERNO, TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_PERSONAS.NOMBRES IS 'Nombre de la persona, NOMBRES, TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_PERSONAS.SEXO IS 'Sexo, SEXO, SELECT';
 
   COMMENT ON COLUMN SISEVENT.MS_PERSONAS.TIPODOCUMENTO IS 'Tipo de documento, TIPO DE DOCUMENTO, SELECT';
 
   COMMENT ON COLUMN SISEVENT.MS_PERSONAS.DOCUMENTO_NUMERO IS 'Número de documento, N° DE DOCUMENTO,TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_PERSONAS.CORREO IS 'Correo electrónico de la persona natural, CORREO, TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_PERSONAS.TELEFONO IS 'Teléfono de la persona natural, TELÉFONO, TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_PERSONAS.CELULAR IS 'Celular de la persona natural, CELULAR, TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_PERSONAS.CODPAIS IS 'Código del país, PAÍS, SELECT, PAI_PK';
 
   COMMENT ON COLUMN SISEVENT.MS_PERSONAS.CODDPTO IS 'Código del departamento según INEI, DEPARTAMENTO, SELECT, CODDPTO';
 
   COMMENT ON COLUMN SISEVENT.MS_PERSONAS.CODPROV IS 'Código de provincia según INEI, PROVINCIA, SELECT, CODPROV';
 
   COMMENT ON COLUMN SISEVENT.MS_PERSONAS.CODDIST IS 'Código de distrito según INEI, DISTRITO, SELECT, CODDIST';
 
   COMMENT ON COLUMN SISEVENT.MS_PERSONAS.DIRECCION IS 'Dirección de la persona natural, DIRECCIÓN, TEXTAREA';
 
   COMMENT ON COLUMN SISEVENT.MS_PERSONAS.TIENEFOTO IS 'Si Tiene o No Fotografía, FOTO, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_PERSONAS.FECHA_CREA IS 'Fecha de creación, FECHA DE CREACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_PERSONAS.FECHA_MODIF IS 'Fecha de modificación, FECHA DE MODIFICACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_PERSONAS.IDUSER_CREA IS 'Usuario que crea, USUARIO QUE CREA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_PERSONAS.IDUSER_MODIF IS 'Usuario que modifica, USUARIO QUE MODIFICA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_PERSONAS.ESTADO IS 'Estado de la persona natural, ESTADO';
 
   COMMENT ON COLUMN SISEVENT.MS_PERSONAS.RMTADDRESS IS 'Dirección de red del que crea, DIRECCIÓN DE RED DEL CREADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_PERSONAS.RMTADDRESSRST IS 'Dirección de red del que modifica, DIRECCIÓN DE RED DEL MODIFICADOR, SISTEMA';
 
   COMMENT ON TABLE SISEVENT.MS_PERSONAS  IS 'PERSONAS NATURALES, DE LA, PERSONA';
 

CREATE TABLE SISEVENT.TD_ANEXOS 
   (	
    IDANEXO NUMBER(10,0) NOT NULL ENABLE, 
	IDEVENT NUMBER(10,0),
    IDFLUJO NUMBER(10,0) NOT NULL ENABLE,
	FILENAME VARCHAR2(255) NOT NULL ENABLE, 
	FILENAMEORIGINAL VARCHAR2(255 CHAR), 
	FECHA_CREA DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	FECHA_MODIF DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	IDUSER_CREA NUMBER(10,0) NOT NULL ENABLE, 
	IDUSER_MODIF NUMBER(10,0) NOT NULL ENABLE, 
	LASTMODIFIED NUMBER(16,0), 
	TAMANIO NUMBER(10,0), 
	TIPO VARCHAR2(100), 
    TABLAA NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	RMTADDRESS VARCHAR2(50) NOT NULL ENABLE, 
	RMTADDRESSRST VARCHAR2(50) NOT NULL ENABLE,	 
	ESTADO NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE
    );

   COMMENT ON COLUMN SISEVENT.TD_ANEXOS.IDANEXO IS 'Código del anexo, ID';
 
   COMMENT ON COLUMN SISEVENT.TD_ANEXOS.IDEVENT IS 'Código de la Atención, Número';
 
   COMMENT ON COLUMN SISEVENT.TD_ANEXOS.TABLAA IS 'Tabla o posición a la que pertenece el anexo, 0, al inicio del evento, 1 al flujo, 2 al itinerario del evento';
  
   COMMENT ON COLUMN SISEVENT.TD_ANEXOS.FILENAME IS 'Archivo en el repositorio, ARCHIVO EN REPOSITORIO';
 
   COMMENT ON COLUMN SISEVENT.TD_ANEXOS.FILENAMEORIGINAL IS 'Archivo, ANEXO, FILE';
 
   COMMENT ON COLUMN SISEVENT.TD_ANEXOS.FECHA_CREA IS 'Fecha de creación, FECHA DE CREACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_ANEXOS.FECHA_MODIF IS 'Fecha de modificación, FECHA DE MODIFICACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_ANEXOS.IDUSER_CREA IS 'Usuario que crea, USUARIO QUE CREA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_ANEXOS.IDUSER_MODIF IS 'USUARIO DEL SISTEMA QUE MODIFICA EL REGISTRO';
 
   COMMENT ON COLUMN SISEVENT.TD_ANEXOS.ESTADO IS 'Usuario que modifica, USUARIO QUE MODIFICA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_ANEXOS.RMTADDRESS IS 'Dirección de red del que crea, DIRECCIÓN DE RED DEL CREADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_ANEXOS.RMTADDRESSRST IS 'Dirección de red del que modifica, DIRECCIÓN DE RED DEL MODIFICADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_ANEXOS.LASTMODIFIED IS 'Última modificación';
 
   COMMENT ON COLUMN SISEVENT.TD_ANEXOS.TAMANIO IS 'Tamaño';
 
   COMMENT ON COLUMN SISEVENT.TD_ANEXOS.TIPO IS 'Tipo';
 
   COMMENT ON COLUMN SISEVENT.TD_ANEXOS.IDFLUJO IS 'Línea de flujo donde se origina';
 
   COMMENT ON TABLE SISEVENT.TD_ANEXOS  IS 'ANEXOS DE LOS MOVIMIENTOS, DEL, ANEXO';
 

CREATE TABLE SISEVENT.TD_FERIADOS 
   (	
    IDFERIADO NUMBER(10,0) NOT NULL ENABLE, 
	FECHA_FERIADO DATE NOT NULL ENABLE, 
	DESCRICION VARCHAR2(255), 
	FECHA_CREA DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	FECHA_MODIF DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	IDUSER_CREA NUMBER(10,0) NOT NULL ENABLE, 
	IDUSER_MODIF NUMBER(10,0) NOT NULL ENABLE,	 
	RMTADDRESS VARCHAR2(50) NOT NULL ENABLE, 
	RMTADDRESSRS VARCHAR2(50) NOT NULL ENABLE,
    ESTADO NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE
    );

   COMMENT ON COLUMN SISEVENT.TD_FERIADOS.IDFERIADO IS 'Código del día feriado, ID';
 
   COMMENT ON COLUMN SISEVENT.TD_FERIADOS.FECHA_FERIADO IS 'Fecha del feriado, FECHA DEL FERIADO';
 
   COMMENT ON COLUMN SISEVENT.TD_FERIADOS.DESCRICION IS 'Descripción del feriado, FERIADO POR';
 
   COMMENT ON COLUMN SISEVENT.TD_FERIADOS.FECHA_CREA IS 'Fecha de creación, FECHA DE CREACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_FERIADOS.FECHA_MODIF IS 'Fecha de modificación, FECHA DE MODIFICACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_FERIADOS.IDUSER_CREA IS 'Usuario que crea, USUARIO QUE CREA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_FERIADOS.IDUSER_MODIF IS 'USUARIO DEL SISTEMA QUE MODIFICA EL REGISTRO';
 
   COMMENT ON COLUMN SISEVENT.TD_FERIADOS.ESTADO IS 'Usuario que modifica, USUARIO QUE MODIFICA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_FERIADOS.RMTADDRESS IS 'Dirección de red del que crea, DIRECCIÓN DE RED DEL CREADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_FERIADOS.RMTADDRESSRS IS 'Dirección de red del que modifica, DIRECCIÓN DE RED DEL QUE MODIFICA';
 
   COMMENT ON TABLE SISEVENT.TD_FERIADOS  IS 'DÍAS NO LABORABLES';
 

CREATE TABLE SISEVENT.TD_FLUJO 
   (	
    IDFLUJO NUMBER(10,0) NOT NULL ENABLE, 
	IDFLUJOPADRE NUMBER(10,0), 
	IDEVENT NUMBER(10,0) NOT NULL ENABLE, 
    IDTAREAS NUMBER(10,0) NOT NULL ENABLE,     
	FECHA_DERIVACION DATE NOT NULL ENABLE, 
	IDUNIDAD_DERIVA NUMBER(10,0) NOT NULL ENABLE, 
	IDUSER_DERIVA NUMBER(10,0) NOT NULL ENABLE, 
	FECHA_RECEPCION DATE, 
	IDUNIDAD_RECEPCIONA NUMBER(10,0), 
	IDUSER_RECEPCIONA NUMBER(10,0), 
	IDUNIDAD_DESTINO NUMBER(10,0) NOT NULL ENABLE, 
	IDUSER_DESTINO NUMBER(10,0) NOT NULL ENABLE, 
	IDUNIDAD_ATIENDE NUMBER(10,0), 
	IDUSER_ATIENDE NUMBER(10,0), 
	FECHA_ATENCION DATE, 
	OBSERVACION VARCHAR2(4000),
    OBSERVACION_HTML VARCHAR2(4000),
	TIEMPOESTADIA NUMBER(4,0),
    CORREOSNOTIF VARCHAR2(250),
	FECHA_CREA DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	FECHA_MODIF DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	IDUSER_CREA NUMBER(10,0) NOT NULL ENABLE, 
	IDUSER_MODIF NUMBER(10,0) NOT NULL ENABLE,	 
	RMTADDRESS VARCHAR2(50) NOT NULL ENABLE, 
	RMTADDRESSRST VARCHAR2(50) NOT NULL ENABLE, 
    ESTADO NUMBER(2,0) DEFAULT 1 NOT NULL ENABLE
    );  
 

   COMMENT ON COLUMN SISEVENT.TD_FLUJO.IDFLUJO IS 'Código del movimiento, ID';
 
   COMMENT ON COLUMN SISEVENT.TD_FLUJO.IDFLUJOPADRE IS 'Código del movimiento padre, DERIVA';
 
   COMMENT ON COLUMN SISEVENT.TD_FLUJO.IDEVENT IS 'Código de la Atención, NÚMERO';
   
   COMMENT ON COLUMN SISEVENT.TD_FLUJO.IDTAREAS IS 'Código de la tarea asignada, NÚMERO';
 
   COMMENT ON COLUMN SISEVENT.TD_FLUJO.FECHA_DERIVACION IS 'Fecha de derivación, FECHA DE DERIVACIÓN';
 
   COMMENT ON COLUMN SISEVENT.TD_FLUJO.IDUNIDAD_DERIVA IS 'Unidad orgánica que deriva, UNIDAD QUE DERIVA';
 
   COMMENT ON COLUMN SISEVENT.TD_FLUJO.IDUSER_DERIVA IS 'Usuario que deriva, USUARIO QUE DERIVA';
 
   COMMENT ON COLUMN SISEVENT.TD_FLUJO.FECHA_RECEPCION IS 'Fecha de recepción, FECHA DE RECEPCIÓN';
 
   COMMENT ON COLUMN SISEVENT.TD_FLUJO.IDUNIDAD_RECEPCIONA IS 'Unidad orgánica que recepciona, UNIDAD QUE RECEPCIONA';
 
   COMMENT ON COLUMN SISEVENT.TD_FLUJO.IDUSER_RECEPCIONA IS 'Usuario que recepciona, UNSUARIO QUE RECEPCIONA';
 
   COMMENT ON COLUMN SISEVENT.TD_FLUJO.IDUNIDAD_DESTINO IS 'Unidad orgánica de destino, UNIDAD DESTINO';
 
   COMMENT ON COLUMN SISEVENT.TD_FLUJO.IDUSER_DESTINO IS 'Usuario destino, USUARIO DESTINO';
 
   COMMENT ON COLUMN SISEVENT.TD_FLUJO.IDUNIDAD_ATIENDE IS 'Unidad orgánica que atiende, UNIDAD QUE ATIENDE';
 
   COMMENT ON COLUMN SISEVENT.TD_FLUJO.IDUSER_ATIENDE IS 'Usuario que atiende, USUARIO QUE ATIENDE';
 
   COMMENT ON COLUMN SISEVENT.TD_FLUJO.FECHA_ATENCION IS 'Fecha de atención, FECHA DE ATENCIÓN';
 
   COMMENT ON COLUMN SISEVENT.TD_FLUJO.OBSERVACION IS 'Detalle de la consulta, DETALLE DE LA CONSULTA';
 
   COMMENT ON COLUMN SISEVENT.TD_FLUJO.TIEMPOESTADIA IS 'Tiempo de estadia, TIEMPO DE ESTADIA';
 
   COMMENT ON COLUMN SISEVENT.TD_FLUJO.FECHA_CREA IS 'Fecha de creación, FECHA DE CREACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_FLUJO.FECHA_MODIF IS 'Fecha de modificación, FECHA DE MODIFICACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_FLUJO.IDUSER_CREA IS 'Usuario que crea, USUARIO QUE CREA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_FLUJO.IDUSER_MODIF IS 'Usuario que modifica, USUARIO QUE MODIFICA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_FLUJO.ESTADO IS 'Estado del movimiento, ESTADO';
 
   COMMENT ON COLUMN SISEVENT.TD_FLUJO.RMTADDRESS IS 'Dirección de red del que crea, DIRECCIÓN DE RED DEL CREADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_FLUJO.RMTADDRESSRST IS 'Dirección de red del que modifica, DIRECCIÓN DE RED DEL MODIFICADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_FLUJO.CORREOSNOTIF IS 'Correo de notificación';
 
   COMMENT ON COLUMN SISEVENT.TD_FLUJO.OBSERVACION_HTML IS 'DETALLE DE LA CONSULTA EN HTML';
 
   COMMENT ON TABLE SISEVENT.TD_FLUJO  IS 'MOVIMIENTOS QUE SE VAN DANDO DENTRO DE LAS ATENCIONES, DEL, MOVIMIENTO';
 
 
 CREATE TABLE SISEVENT.MS_CATEGORIAS 
   (	
    IDCATEGORIAS NUMBER(10,0) NOT NULL ENABLE, 
	CATEGORIA VARCHAR2(150) NOT NULL ENABLE, 
    ARRAYCAMPOSOCULTOS VARCHAR2(500) NOT NULL ENABLE,
	FECHA_CREA DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	FECHA_MODIF DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	IDUSER_CREA NUMBER(10,0) NOT NULL ENABLE, 
	IDUSER_MODIF NUMBER(10,0) NOT NULL ENABLE, 
	RMTADDRESS VARCHAR2(50) NOT NULL ENABLE, 
	RMTADDRESSRST VARCHAR2(50) NOT NULL ENABLE,	 
	ESTADO NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE
    );

   COMMENT ON COLUMN SISEVENT.MS_CATEGORIAS.IDCATEGORIAS IS 'Código de la categoria, ID';
 
   COMMENT ON COLUMN SISEVENT.MS_CATEGORIAS.ARRAYCAMPOSOCULTOS IS 'Array separado por | de los campos que se deben ocultar al seleccionar la categoria';
 
   COMMENT ON COLUMN SISEVENT.MS_CATEGORIAS.CATEGORIA IS 'Categoría asignada, Categoría';
 
   COMMENT ON COLUMN SISEVENT.MS_CATEGORIAS.FECHA_CREA IS 'Fecha de creación, FECHA DE CREACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_CATEGORIAS.FECHA_MODIF IS 'Fecha de modificación, FECHA DE MODIFICACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_CATEGORIAS.IDUSER_CREA IS 'Usuario que crea, USUARIO QUE CREA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_CATEGORIAS.IDUSER_MODIF IS 'USUARIO DEL SISTEMA QUE MODIFICA EL REGISTRO';
 
   COMMENT ON COLUMN SISEVENT.MS_CATEGORIAS.ESTADO IS 'Usuario que modifica, USUARIO QUE MODIFICA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_CATEGORIAS.RMTADDRESS IS 'Dirección de red del que crea, DIRECCIÓN DE RED DEL CREADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_CATEGORIAS.RMTADDRESSRST IS 'Dirección de red del que modifica, DIRECCIÓN DE RED DEL MODIFICADOR, SISTEMA';
 
   COMMENT ON TABLE SISEVENT.MS_CATEGORIAS  IS 'CATEGORÍAS ASIGADOS A LOS EVENTOS';
   
CREATE TABLE SISEVENT.TD_PARTICIPANTES 
   (	
    IDPARTICIPANTES NUMBER(10,0) NOT NULL ENABLE, 
    IDUSUARIO_IDPROVEE_IDPERSON NUMBER(10,0) NOT NULL ENABLE,	
    NOMBRESRAZONSOCIAL VARCHAR2(600) NOT NULL ENABLE,
    TIPO NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
    FLAGACOMPANIANTE NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
    FECHA_CREA DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	FECHA_MODIF DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	IDUSER_CREA NUMBER(10,0) NOT NULL ENABLE, 
	IDUSER_MODIF NUMBER(10,0) NOT NULL ENABLE, 
	RMTADDRESS VARCHAR2(50) NOT NULL ENABLE, 
	RMTADDRESSRST VARCHAR2(50) NOT NULL ENABLE,	 
	ESTADO NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE
    );

   COMMENT ON COLUMN SISEVENT.TD_PARTICIPANTES.IDPARTICIPANTES IS 'Código del participante, ID';
 
   COMMENT ON COLUMN SISEVENT.TD_PARTICIPANTES.IDUSUARIO_IDPROVEE_IDPERSON IS 'ID de la persona o institución seleccionada, Código del participante';
 
   COMMENT ON COLUMN SISEVENT.TD_PARTICIPANTES.NOMBRESRAZONSOCIAL IS 'Nombre o razón social del participante, Nombre';
   
   COMMENT ON COLUMN SISEVENT.TD_PARTICIPANTES.TIPO IS 'Tipo de participante, Institución, persona o usuario';

   COMMENT ON COLUMN SISEVENT.TD_PARTICIPANTES.FLAGACOMPANIANTE IS 'Es 1 si es acompañante, si no participante';
 
   COMMENT ON COLUMN SISEVENT.TD_PARTICIPANTES.FECHA_CREA IS 'Fecha de creación, FECHA DE CREACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_PARTICIPANTES.FECHA_MODIF IS 'Fecha de modificación, FECHA DE MODIFICACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_PARTICIPANTES.IDUSER_CREA IS 'Usuario que crea, USUARIO QUE CREA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_PARTICIPANTES.IDUSER_MODIF IS 'USUARIO DEL SISTEMA QUE MODIFICA EL REGISTRO';
 
   COMMENT ON COLUMN SISEVENT.TD_PARTICIPANTES.ESTADO IS 'Usuario que modifica, USUARIO QUE MODIFICA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_PARTICIPANTES.RMTADDRESS IS 'Dirección de red del que crea, DIRECCIÓN DE RED DEL CREADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_PARTICIPANTES.RMTADDRESSRST IS 'Dirección de red del que modifica, DIRECCIÓN DE RED DEL MODIFICADOR, SISTEMA';
 
   COMMENT ON TABLE SISEVENT.TD_PARTICIPANTES  IS 'PARTICIPANTES O ACOMPAÑANTES ASIGADOS A LOS EVENTOS';   
 
 CREATE TABLE SISEVENT.TD_UBICACIONES
   (	
    IDUBICACIONES NUMBER(10,0) NOT NULL ENABLE, 
	IDEVENT NUMBER(10,0),
    CODPAIS NUMBER(10,0) DEFAULT null, 
	CODDPTO NUMBER(2,0) DEFAULT null, 
	CODPROV NUMBER(2,0) DEFAULT null, 
	CODDIST NUMBER(2,0) DEFAULT null, 
	UBICACION VARCHAR2(550) NOT NULL ENABLE,
    FECHA_ACTIV_INI DATE NOT NULL ENABLE,
    FECHA_ACTIV_FIN DATE NOT NULL ENABLE,
	FECHA_CREA DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	FECHA_MODIF DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	IDUSER_CREA NUMBER(10,0) NOT NULL ENABLE, 
	IDUSER_MODIF NUMBER(10,0) NOT NULL ENABLE, 
	RMTADDRESS VARCHAR2(50) NOT NULL ENABLE, 
	RMTADDRESSRST VARCHAR2(50) NOT NULL ENABLE,	 
	ESTADO NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE
    );

   COMMENT ON COLUMN SISEVENT.TD_UBICACIONES.IDCATEGORIAS IS 'Código de la categoria, ID';
 
   COMMENT ON COLUMN SISEVENT.TD_UBICACIONES.IDEVENT IS 'Código del evento, Número';
 
   COMMENT ON COLUMN SISEVENT.TD_UBICACIONES.CODPAIS IS 'Código del país, PAÍS, SELECT, PAI_PK';
 
   COMMENT ON COLUMN SISEVENT.TD_UBICACIONES.CODDPTO IS 'Código del departamento según INEI, DEPARTAMENTO, SELECT-P, CODDPTO';
 
   COMMENT ON COLUMN SISEVENT.TD_UBICACIONES.CODPROV IS 'Código de provincia según INEI, PROVINCIA, SELECT-M, CODPROV';
 
   COMMENT ON COLUMN SISEVENT.TD_UBICACIONES.CODDIST IS 'Código de distrito según INEI, DISTRITO, SELECT-H, CODDIST';
 
   COMMENT ON COLUMN SISEVENT.TD_UBICACIONES.UBICACION IS 'Ubicación de la Institución o Entidad donde se realiza el evento, UBICACIÓN, TEXTAREA';
 
   COMMENT ON COLUMN SISEVENT.TD_UBICACIONES.FECHA_ACTIV_INI IS 'Fecha y hora de inicio del evento, Fecha y hora inicial';
   
   COMMENT ON COLUMN SISEVENT.TD_UBICACIONES.FECHA_ACTIV_INI IS 'Fecha y hora de inicio del evento, Fecha y hora final';
 
   COMMENT ON COLUMN SISEVENT.TD_UBICACIONES.FECHA_CREA IS 'Fecha de creación, FECHA DE CREACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_UBICACIONES.FECHA_MODIF IS 'Fecha de modificación, FECHA DE MODIFICACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_UBICACIONES.IDUSER_CREA IS 'Usuario que crea, USUARIO QUE CREA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_UBICACIONES.IDUSER_MODIF IS 'USUARIO DEL SISTEMA QUE MODIFICA EL REGISTRO';
 
   COMMENT ON COLUMN SISEVENT.TD_UBICACIONES.ESTADO IS 'Usuario que modifica, USUARIO QUE MODIFICA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_UBICACIONES.RMTADDRESS IS 'Dirección de red del que crea, DIRECCIÓN DE RED DEL CREADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_UBICACIONES.RMTADDRESSRST IS 'Dirección de red del que modifica, DIRECCIÓN DE RED DEL MODIFICADOR, SISTEMA';
 
   COMMENT ON TABLE SISEVENT.TD_UBICACIONES  IS 'UBICACIONES ASIGADOS A LOS EVENTOS';
 
 
 CREATE TABLE SISEVENT.MS_TAREAS 
   (	
    IDTAREAS NUMBER(10,0) NOT NULL ENABLE, 
	TAREA VARCHAR2(150) NOT NULL ENABLE, 
	DESCRIPCION VARCHAR2(500),	
    TIEMPO NUMBER(10,0),	
    IDUSER_CREA NUMBER(10,0) NOT NULL ENABLE, 
	IDUSER_MODIF NUMBER(10,0) NOT NULL ENABLE, 
	FECHA_CREA DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	FECHA_MODIF DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	RTMADDRESS VARCHAR2(50) NOT NULL ENABLE, 
	RTMADDRESSMODIF VARCHAR2(50) NOT NULL ENABLE, 
	ESTADO NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE
    ); 

   COMMENT ON COLUMN SISEVENT.MS_TAREAS.IDTAREAS IS 'Código de la tarea, ID';
 
   COMMENT ON COLUMN SISEVENT.MS_TAREAS.DESCRIPCION IS 'Descripción de la tarea, TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_TAREAS.TAREA IS 'Nombre de la tarea, TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_TAREAS.TIEMPO IS 'Tiempo en días laborables para cumplir con la tarea, Días, NUMBER';
 
   COMMENT ON COLUMN SISEVENT.MS_TAREAS.IDUSER_CREA IS 'Usuario que crea, USUARIO QUE CREA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_TAREAS.IDUSER_MODIF IS 'Usuario que modifica, USUARIO QUE MODIFICA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_TAREAS.FECHA_CREA IS 'Fecha de creación, FECHA DE CREACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_TAREAS.FECHA_MODIF IS 'Fecha de modificación, FECHA DE MODIFICACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_TAREAS.RTMADDRESS IS 'Dirección de red del que crea, DIRECCIÓN DE RED DEL CREADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_TAREAS.RTMADDRESSMODIF IS 'Dirección de red del que modifica, DIRECCIÓN DE RED DEL MODIFICADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_TAREAS.ESTADO IS 'Estado del paámetro, ESTADO';
 
   COMMENT ON TABLE SISEVENT.MS_TAREAS  IS 'ALMACENA LAS TAREAS QUE SE APLICARÁN EN LAS DERIVACIONES';
 
  CREATE TABLE SISEVENT.MS_ACTIVIDADES 
   (	
    IDACTIVIDADES NUMBER(10,0) NOT NULL ENABLE,
    IDTAREAS NUMBER(10,0) NOT NULL ENABLE, 
	ACTIVIDAD VARCHAR2(150) NOT NULL ENABLE, 
	CAMPOSALLENAR VARCHAR2(500),	
    NUMERODIGITALES NUMBER(4,0),	
    IDUSER_CREA NUMBER(10,0) NOT NULL ENABLE, 
	IDUSER_MODIF NUMBER(10,0) NOT NULL ENABLE, 
	FECHA_CREA DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	FECHA_MODIF DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	RTMADDRESS VARCHAR2(50) NOT NULL ENABLE, 
	RTMADDRESSMODIF VARCHAR2(50) NOT NULL ENABLE, 
	ESTADO NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE
    ); 

   COMMENT ON COLUMN SISEVENT.MS_ACTIVIDADES.IDACTIVIDADES IS 'Código de la actividad, ID';
 
   COMMENT ON COLUMN SISEVENT.MS_ACTIVIDADES.IDTAREAS IS 'Código de la tarea a la que pertenece, Tarea';
 
   COMMENT ON COLUMN SISEVENT.MS_ACTIVIDADES.ACTIVIDAD IS 'Descripción de la actividad, TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_ACTIVIDADES.CAMPOSALLENAR IS 'Nombre del campo que se deben llenar antes de terminar la tarea, Campos, TEXT';
 
   COMMENT ON COLUMN SISEVENT.MS_ACTIVIDADES.NUMERODIGITALES IS 'Número minimo de digitales, que se debe cargar, antes de terminar la tarea, Días, NUMBER';
 
   COMMENT ON COLUMN SISEVENT.MS_ACTIVIDADES.IDUSER_CREA IS 'Usuario que crea, USUARIO QUE CREA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_ACTIVIDADES.IDUSER_MODIF IS 'Usuario que modifica, USUARIO QUE MODIFICA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_ACTIVIDADES.FECHA_CREA IS 'Fecha de creación, FECHA DE CREACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_ACTIVIDADES.FECHA_MODIF IS 'Fecha de modificación, FECHA DE MODIFICACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_ACTIVIDADES.RTMADDRESS IS 'Dirección de red del que crea, DIRECCIÓN DE RED DEL CREADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_ACTIVIDADES.RTMADDRESSMODIF IS 'Dirección de red del que modifica, DIRECCIÓN DE RED DEL MODIFICADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.MS_ACTIVIDADES.ESTADO IS 'Estado del paámetro, ESTADO';
 
   COMMENT ON TABLE SISEVENT.MS_ACTIVIDADES  IS 'ALMACENA LAS ACTIVIDADES QUE SE APLICARÁN EN LAS TAREAS';
 
 CREATE TABLE SISEVENT.TD_ITINERARIO
   (	
    IDITINERARIO NUMBER(10,0) NOT NULL ENABLE, 
	IDEVENT NUMBER(10,0),
    CODPAIS NUMBER(10,0) DEFAULT null, 
	CODDPTO NUMBER(2,0) DEFAULT null, 
	CODPROV NUMBER(2,0) DEFAULT null, 
	ORIGENDESTINO VARCHAR2(550) NOT NULL ENABLE,
    FECHA_SALI_INI DATE NOT NULL ENABLE,
    FECHA_LLEG_FIN DATE NOT NULL ENABLE,
	FECHA_CREA DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	FECHA_MODIF DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	IDUSER_CREA NUMBER(10,0) NOT NULL ENABLE, 
	IDUSER_MODIF NUMBER(10,0) NOT NULL ENABLE, 
	RMTADDRESS VARCHAR2(50) NOT NULL ENABLE, 
	RMTADDRESSRST VARCHAR2(50) NOT NULL ENABLE,	 
	ESTADO NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE
    );

   COMMENT ON COLUMN SISEVENT.TD_ITINERARIO.IDCATEGORIAS IS 'Código de la categoria, ID';
 
   COMMENT ON COLUMN SISEVENT.TD_ITINERARIO.IDEVENT IS 'Código del evento, Número';
 
   COMMENT ON COLUMN SISEVENT.TD_ITINERARIO.CODPAIS IS 'Código del país, PAÍS, SELECT, PAI_PK';
 
   COMMENT ON COLUMN SISEVENT.TD_ITINERARIO.CODDPTO IS 'Código del departamento según INEI, DEPARTAMENTO, SELECT-P, CODDPTO';
 
   COMMENT ON COLUMN SISEVENT.TD_ITINERARIO.CODPROV IS 'Código de provincia según INEI, PROVINCIA, SELECT-M, CODPROV';
 
   COMMENT ON COLUMN SISEVENT.TD_ITINERARIO.CODDIST IS 'Código de distrito según INEI, DISTRITO, SELECT-H, CODDIST';
 
   COMMENT ON COLUMN SISEVENT.TD_ITINERARIO.UBICACION IS 'Ubicación de la Institución o Entidad donde se realiza el evento, UBICACIÓN, TEXTAREA';
 
   COMMENT ON COLUMN SISEVENT.TD_ITINERARIO.FECHA_ACTIV_INI IS 'Fecha y hora de inicio del evento, Fecha y hora inicial';
   
   COMMENT ON COLUMN SISEVENT.TD_ITINERARIO.FECHA_ACTIV_INI IS 'Fecha y hora de inicio del evento, Fecha y hora final';
 
   COMMENT ON COLUMN SISEVENT.TD_ITINERARIO.FECHA_CREA IS 'Fecha de creación, FECHA DE CREACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_ITINERARIO.FECHA_MODIF IS 'Fecha de modificación, FECHA DE MODIFICACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_ITINERARIO.IDUSER_CREA IS 'Usuario que crea, USUARIO QUE CREA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_ITINERARIO.IDUSER_MODIF IS 'USUARIO DEL SISTEMA QUE MODIFICA EL REGISTRO';
 
   COMMENT ON COLUMN SISEVENT.TD_ITINERARIO.ESTADO IS 'Usuario que modifica, USUARIO QUE MODIFICA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_ITINERARIO.RMTADDRESS IS 'Dirección de red del que crea, DIRECCIÓN DE RED DEL CREADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_ITINERARIO.RMTADDRESSRST IS 'Dirección de red del que modifica, DIRECCIÓN DE RED DEL MODIFICADOR, SISTEMA';
 
   COMMENT ON TABLE SISEVENT.TD_ITINERARIO  IS 'ITINERARIO DE LOS VUELOS A REALIZARCE';
 
CREATE TABLE SISEVENT.TD_EVENTO 
   (	
    IDEVENT NUMBER(10,0) NOT NULL ENABLE, 
	TITULO  VARCHAR2(600) NOT NULL ENABLE,
    FECHA_SOLI_INI DATE NOT NULL ENABLE,
    FECHA_SOLI_FIN DATE NOT NULL ENABLE,
    PORCONFIRMAR NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
    IDDOC NUMBER(10,0),
    NUMERO_SID VARCHAR2(50), 
	NUMERO_ANIO_SID NUMBER(4,0),
    ASUNTOHR  VARCHAR2(600) NOT NULL ENABLE,
	REMI_RAZON_SOCIAL VARCHAR2(255),
    REMI_IDPROVEE NUMBER(10,0), 
    REMI_NOMBRESAPELLIDOS VARCHAR2(350), 
    REMI_IDPERSON NUMBER(10,0), 
    TIPOEVENTO VARCHAR2(150) DEFAULT 'OTRO',
    IDCATEGORIAS NUMBER(10,0) NOT NULL ENABLE,
    MODALIDAD VARCHAR2(150) DEFAULT 'OTROS', 
	FECHA_CREA DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	FECHA_MODIF DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	IDUSER_CREA NUMBER(10,0) NOT NULL ENABLE, 
	IDUSER_MODIF NUMBER(10,0) NOT NULL ENABLE,	 
	RMTADDRESS VARCHAR2(50) NOT NULL ENABLE, 
	RMTADDRESSRST VARCHAR2(50) NOT NULL ENABLE, 
	ESTADO NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE
    );

   COMMENT ON COLUMN SISEVENT.TD_EVENTO.IDEVENT IS 'Código del evento, ID';
      
   COMMENT ON COLUMN SISEVENT.TD_EVENTO.TITULO IS 'Título del evento';
 
   COMMENT ON COLUMN SISEVENT.TD_EVENTO.FECHA_SOLI_INI IS 'Fecha y hora de la solicitud';
   
   COMMENT ON COLUMN SISEVENT.TD_EVENTO.FECHA_SOLI_FIN IS 'Fecha y hora en la que termina el evento';

   COMMENT ON COLUMN SISEVENT.TD_EVENTO.PORCONFIRMAR IS 'Bandera que determina si la fecha esta por confirmar, Fecha por confirmar, BOOLEAN';   
   
   COMMENT ON COLUMN SISEVENT.TD_EVENTO.IDDOC IS 'ID de la hoja de ruta relacionada';
      
   COMMENT ON COLUMN SISEVENT.TD_EVENTO.NUMERO_SID IS 'Número de Hoja de Ruta, Número de Hoja de Ruta, TEXT';
 
   COMMENT ON COLUMN SISEVENT.TD_EVENTO.NUMERO_ANIO_SID IS 'Año de la Hoja de Ruta, AÑO DE LA HOJA DE RUTA, NUMBER';
 
   COMMENT ON COLUMN SISEVENT.TD_EVENTO.ASUNTOHR IS 'Asunto de la hoja de ruta relacionada, Asunto-HR';
 
   COMMENT ON COLUMN SISEVENT.TD_EVENTO.REMI_RAZON_SOCIAL IS 'Razón social de la HR que remite, de ser el caso, Razón social';

   COMMENT ON COLUMN SISEVENT.TD_EVENTO.REMI_IDPROVEE IS 'ID de la Razón social que remite, ID de Razón social';
   
   COMMENT ON COLUMN SISEVENT.TD_EVENTO.REMI_NOMBRESAPELLIDOS IS 'Nombres y apellidos de la persona que remite, Nombre y apellidos del remitente';
   
   COMMENT ON COLUMN SISEVENT.TD_EVENTO.REMI_IDPERSON IS 'ID de la persona que remite, ID del remitente';
   
   COMMENT ON COLUMN SISEVENT.TD_EVENTO.TIPOEVENTO IS 'Tipo de evento, Tipo de evento';
   
   COMMENT ON COLUMN SISEVENT.TD_EVENTO.IDCATEGORIAS IS 'Categoría del evento, Categoría del evento';
   
   COMMENT ON COLUMN SISEVENT.TD_EVENTO.MODALIDAD IS 'Modalidad del evento, Modalidad';
   
   COMMENT ON COLUMN SISEVENT.TD_EVENTO.FECHA_CREA IS 'Fecha de creación, FECHA DE CREACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_EVENTO.FECHA_MODIF IS 'Fecha de modificación, FECHA DE MODIFICACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_EVENTO.IDUSER_CREA IS 'Usuario que crea, USUARIO QUE CREA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_EVENTO.IDUSER_MODIF IS 'Usuario que modifica, USUARIO QUE MODIFICA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_EVENTO.ESTADO IS 'Estado del movimiento, ESTADO';
 
   COMMENT ON COLUMN SISEVENT.TD_EVENTO.RMTADDRESS IS 'Dirección de red del que crea, DIRECCIÓN DE RED DEL CREADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_EVENTO.RMTADDRESSRST IS 'Dirección de red del que modifica, DIRECCIÓN DE RED DEL MODIFICADOR, SISTEMA';
 
   COMMENT ON TABLE SISEVENT.TD_EVENTO  IS 'EVENTO';
 
CREATE TABLE SISEVENT.TD_GRUPOS
   (	
    IDGRUPO NUMBER(10,0) NOT NULL ENABLE, 
	GRUPO VARCHAR2(150) NOT NULL ENABLE, 
    FECHA_CREA DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	FECHA_MODIF DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	IDUSER_CREA NUMBER(10,0) NOT NULL ENABLE, 
	IDUSER_MODIF NUMBER(10,0) NOT NULL ENABLE, 
	RMTADDRESS VARCHAR2(50) NOT NULL ENABLE, 
	RMTADDRESSRST VARCHAR2(50) NOT NULL ENABLE,	 
	ESTADO NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE
    );

   COMMENT ON COLUMN SISEVENT.TD_GRUPOS.IDGRUPO IS 'Código del grupo, ID';
 
   COMMENT ON COLUMN SISEVENT.TD_GRUPOS.GRUPO IS 'Nombre del grupo, Grupo';
 
   COMMENT ON COLUMN SISEVENT.TD_GRUPOS.FECHA_CREA IS 'Fecha de creación, FECHA DE CREACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_GRUPOS.FECHA_MODIF IS 'Fecha de modificación, FECHA DE MODIFICACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_GRUPOS.IDUSER_CREA IS 'Usuario que crea, USUARIO QUE CREA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_GRUPOS.IDUSER_MODIF IS 'USUARIO DEL SISTEMA QUE MODIFICA EL REGISTRO';
 
   COMMENT ON COLUMN SISEVENT.TD_GRUPOS.ESTADO IS 'Usuario que modifica, USUARIO QUE MODIFICA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_GRUPOS.RMTADDRESS IS 'Dirección de red del que crea, DIRECCIÓN DE RED DEL CREADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_GRUPOS.RMTADDRESSRST IS 'Dirección de red del que modifica, DIRECCIÓN DE RED DEL MODIFICADOR, SISTEMA';
 
   COMMENT ON TABLE SISEVENT.TD_GRUPOS IS 'GRUPOS DE FLUJOS QUE SE ASIGNAN A LOS EVENTOS';
   
   
   CREATE TABLE SISEVENT.TD_GRUPOSFLUJOS 
   (	
    IDGRUPOSFLUJOS NUMBER(10,0) NOT NULL ENABLE, 
    IDGRUPO NUMBER(10,0) NOT NULL ENABLE,
	IDTAREAS NUMBER(10,0) NOT NULL ENABLE,     
	IDUNIDAD_DESTINO NUMBER(10,0) NOT NULL ENABLE, 
	IDUSER_DESTINO NUMBER(10,0) NOT NULL ENABLE, 
	OBSERVACION VARCHAR2(4000),
    OBSERVACION_HTML VARCHAR2(4000),
	TIEMPOESTADIA NUMBER(4,0),
    CORREOSNOTIF VARCHAR2(250),
	FECHA_CREA DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	FECHA_MODIF DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	IDUSER_CREA NUMBER(10,0) NOT NULL ENABLE, 
	IDUSER_MODIF NUMBER(10,0) NOT NULL ENABLE,	 
	RMTADDRESS VARCHAR2(50) NOT NULL ENABLE, 
	RMTADDRESSRST VARCHAR2(50) NOT NULL ENABLE, 
    ESTADO NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE
    );  
 

   COMMENT ON COLUMN SISEVENT.TD_GRUPOSFLUJOS.IDGRUPOSFLUJOS IS 'Código del movimiento, ID';
 
   COMMENT ON COLUMN SISEVENT.TD_GRUPOSFLUJOS.IDTAREAS IS 'Código de la tarea asignada, Tarea';
 
   COMMENT ON COLUMN SISEVENT.TD_GRUPOSFLUJOS.IDUNIDAD_DESTINO IS 'Unidad orgánica de destino, UNIDAD DESTINO';
 
   COMMENT ON COLUMN SISEVENT.TD_GRUPOSFLUJOS.IDUSER_DESTINO IS 'Usuario destino, USUARIO DESTINO';
 
   COMMENT ON COLUMN SISEVENT.TD_GRUPOSFLUJOS.OBSERVACION IS 'Detalle de la consulta, DETALLE DE LA CONSULTA';
 
   COMMENT ON COLUMN SISEVENT.TD_GRUPOSFLUJOS.TIEMPOESTADIA IS 'Tiempo de estadia, TIEMPO DE ESTADIA';
 
   COMMENT ON COLUMN SISEVENT.TD_GRUPOSFLUJOS.FECHA_CREA IS 'Fecha de creación, FECHA DE CREACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_GRUPOSFLUJOS.FECHA_MODIF IS 'Fecha de modificación, FECHA DE MODIFICACIÓN, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_GRUPOSFLUJOS.IDUSER_CREA IS 'Usuario que crea, USUARIO QUE CREA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_GRUPOSFLUJOS.IDUSER_MODIF IS 'Usuario que modifica, USUARIO QUE MODIFICA, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_GRUPOSFLUJOS.ESTADO IS 'Estado del movimiento, ESTADO';
 
   COMMENT ON COLUMN SISEVENT.TD_GRUPOSFLUJOS.RMTADDRESS IS 'Dirección de red del que crea, DIRECCIÓN DE RED DEL CREADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_GRUPOSFLUJOS.RMTADDRESSRST IS 'Dirección de red del que modifica, DIRECCIÓN DE RED DEL MODIFICADOR, SISTEMA';
 
   COMMENT ON COLUMN SISEVENT.TD_GRUPOSFLUJOS.CORREOSNOTIF IS 'Correo de notificación';
 
   COMMENT ON COLUMN SISEVENT.TD_GRUPOSFLUJOS.OBSERVACION_HTML IS 'DETALLE DE LA CONSULTA EN HTML';
 
   COMMENT ON TABLE SISEVENT.TD_GRUPOSFLUJOS  IS 'MOVIMIENTOS QUE SE VAN DANDO DENTRO DEL GRUPO, EL, GRUPO';
   
   
ALTER TABLE SISEVENT.MS_ACTIVIDADES
ADD CONSTRAINT MS_ACTIVIDADES_PK PRIMARY KEY 
(
  IDACTIVIDADES 
)
ENABLE;

CREATE INDEX MS_ACTIVIDADES_TAREA ON SISEVENT.MS_ACTIVIDADES (IDTAREAS DESC);

ALTER TABLE SISEVENT.MS_CATEGORIAS
ADD CONSTRAINT MS_CATEGORIAS_PK PRIMARY KEY 
(
  IDCATEGORIAS 
)
ENABLE;

CREATE INDEX MS_INSTITUCIONES_IDXRAZON ON SISEVENT.MS_INSTITUCIONES (RAZON_SOCIAL ASC);

CREATE INDEX MS_INSTITUCIONES_IDXRUC ON SISEVENT.MS_INSTITUCIONES (RUC ASC);

ALTER TABLE SISEVENT.MS_INSTITUCIONES
ADD CONSTRAINT MS_INSTITUCIONES_PK PRIMARY KEY 
(
  IDPROVEE 
)
ENABLE;

CREATE INDEX MS_PAISES_IDZPAIS ON SISEVENT.MS_PAISES (PAI_NOMBRE ASC);

ALTER TABLE SISEVENT.MS_PAISES
ADD CONSTRAINT MS_PAISES_PK PRIMARY KEY 
(
  PAI_PK 
)
ENABLE;

CREATE INDEX MS_PERSONAS_IDXMATERNO ON SISEVENT.MS_PERSONAS (APELLIDO_MATERNO ASC);

CREATE INDEX MS_PERSONAS_IDXNOMBRES ON SISEVENT.MS_PERSONAS (NOMBRES ASC);

CREATE INDEX MS_PERSONAS_IDXPATERNO ON SISEVENT.MS_PERSONAS (APELLIDO_PATERNO ASC);

ALTER TABLE SISEVENT.MS_PERSONAS
ADD CONSTRAINT MS_PERSONAS_PK PRIMARY KEY 
(
  IDPERSON 
)
ENABLE;

CREATE INDEX MS_ROLES_IDXUSERNAME ON SISEVENT.MS_ROLES (USERNAME ASC);

ALTER TABLE SISEVENT.MS_ROLES
ADD CONSTRAINT MS_ROLES_PK PRIMARY KEY 
(
  IDROL 
)
ENABLE;

ALTER TABLE SISEVENT.MS_TAREAS
ADD CONSTRAINT MS_TAREAS_PK PRIMARY KEY 
(
  IDTAREAS 
)
ENABLE;

CREATE INDEX MS_UBIGEO_IDXDPTO ON SISEVENT.MS_UBIGEO (CODDPTO ASC);

CREATE INDEX MS_UBIGEO_IDXPROV ON SISEVENT.MS_UBIGEO (CODPROV ASC);

CREATE INDEX MS_UBIGEO_INDDIST ON SISEVENT.MS_UBIGEO (CODDIST ASC);

ALTER TABLE SISEVENT.MS_UBIGEO
ADD CONSTRAINT MS_UBIGEO_PK PRIMARY KEY 
(
  CODDPTO 
, CODPROV 
, CODDIST 
)
ENABLE;

CREATE INDEX MS_UNIDADES_ORG_IDXCODIGO ON SISEVENT.MS_UNIDADES_ORG (CODIGO);

CREATE INDEX MS_UNIDADES_ORG_IDXEST ON SISEVENT.MS_UNIDADES_ORG (DESCRIPCION);

CREATE INDEX MS_UNIDADES_ORG_IDXFLAG ON SISEVENT.MS_UNIDADES_ORG (FLAGOFGENERAL);

CREATE INDEX MS_UNIDADES_ORG_IDXPADRE ON SISEVENT.MS_UNIDADES_ORG (IDPADRE ASC);

ALTER TABLE SISEVENT.MS_UNIDADES_ORG
ADD CONSTRAINT MS_UNIDADES_ORG_PK PRIMARY KEY 
(
  IDUNIDAD 
)
ENABLE;

CREATE INDEX MS_ACTIVIDADES_IDXEST ON SISEVENT.MS_ACTIVIDADES (ESTADO ASC);
CREATE INDEX MS_CATEGORIAS_IDXEST ON SISEVENT.MS_CATEGORIAS (ESTADO ASC);
CREATE INDEX MS_INSTITUCIONES_IDXEST ON SISEVENT.MS_INSTITUCIONES (ESTADO ASC);
CREATE INDEX MS_PAISES_IDXEST ON SISEVENT.MS_PAISES (ESTADO ASC);
CREATE INDEX MS_PERSONAS_IDXEST ON SISEVENT.MS_PERSONAS (ESTADO ASC);
CREATE INDEX MS_ROLES_IDXEST ON SISEVENT.MS_ROLES (ESTADO ASC);
CREATE INDEX MS_TAREAS_IDXEST ON SISEVENT.MS_TAREAS (TAREA ASC);
CREATE INDEX MS_UBIGEO_IDXEST ON SISEVENT.MS_UBIGEO (ESTADO ASC);
CREATE INDEX MS_UBIGEO_IDXNOMBRE ON SISEVENT.MS_UBIGEO (NOMBRE ASC);

CREATE INDEX MS_USUARIOS_IDXEST ON SISEVENT.MS_USUARIOS (ESTADO ASC);

CREATE UNIQUE INDEX MS_USUARIOS_IDXUSERNAME ON SISEVENT.MS_USUARIOS (USERNAME ASC);

ALTER TABLE SISEVENT.MS_USUARIOS
ADD CONSTRAINT MS_USUARIOS_PK PRIMARY KEY 
(
  IDUSUARIO 
)
ENABLE;

CREATE INDEX PRT_PARAMETROS_IDXEST ON SISEVENT.PRT_PARAMETROS (ESTADO ASC);

CREATE INDEX PRT_PARAMETROS_IDXPADRE ON SISEVENT.PRT_PARAMETROS (IDPADRE ASC);

CREATE INDEX PRT_PARAMETROS_IDXPARA ON SISEVENT.PRT_PARAMETROS (DESCRIPCION ASC);

ALTER TABLE SISEVENT.PRT_PARAMETROS
ADD CONSTRAINT PRT_PARAMETROS_PK PRIMARY KEY 
(
  IDPARAMETRO 
)
ENABLE;

CREATE INDEX TD_ANEXOS_IDXEST ON SISEVENT.TD_ANEXOS (ESTADO ASC);

CREATE INDEX TD_ANEXOS_IDXEVENT ON SISEVENT.TD_ANEXOS (IDEVENT ASC);

CREATE INDEX TD_ANEXOS_IDXFLUJO ON SISEVENT.TD_ANEXOS (IDFLUJO ASC);

CREATE INDEX TD_ANEXOS_IDXTABLA ON SISEVENT.TD_ANEXOS (TABLAA ASC);

ALTER TABLE SISEVENT.TD_ANEXOS
ADD CONSTRAINT TD_ANEXOS_PK PRIMARY KEY 
(
  IDANEXO 
)
ENABLE;

CREATE INDEX TD_EVENTO_IDXCATEGORIA ON SISEVENT.TD_EVENTO (IDCATEGORIAS ASC);

CREATE INDEX TD_EVENTO_IDXEST ON SISEVENT.TD_EVENTO (ESTADO ASC);

CREATE INDEX TD_EVENTO_IDXFECHFIN ON SISEVENT.TD_EVENTO (TRUNC(FECHA_SOLI_FIN) ASC);

CREATE INDEX TD_EVENTO_IDXFECHINI ON SISEVENT.TD_EVENTO (TRUNC(FECHA_SOLI_INI) ASC);

CREATE INDEX TD_EVENTO_IDXIDPERSONA ON SISEVENT.TD_EVENTO (REMI_IDPERSON ASC);

CREATE INDEX TD_EVENTO_IDXIDPROV ON SISEVENT.TD_EVENTO (REMI_IDPROVEE ASC);

CREATE INDEX TD_EVENTO_IDXMODALIDAD ON SISEVENT.TD_EVENTO (MODALIDAD ASC);

CREATE INDEX TD_EVENTO_IDXNUMEROSID ON SISEVENT.TD_EVENTO (NUMERO_SID||'-'||NUMERO_ANIO_SID ASC);

CREATE INDEX TD_EVENTO_IDXPERSONA ON SISEVENT.TD_EVENTO (REMI_NOMBRESAPELLIDOS ASC);

CREATE INDEX TD_EVENTO_IDXPORCONFIRMAR ON SISEVENT.TD_EVENTO (PORCONFIRMAR ASC);

CREATE INDEX TD_EVENTO_IDXRAZON ON SISEVENT.TD_EVENTO (REMI_RAZON_SOCIAL ASC);

CREATE INDEX TD_EVENTO_IDXTIPOEVENT ON SISEVENT.TD_EVENTO (TIPOEVENTO ASC);

CREATE INDEX TD_EVENTO_IDXTITULO ON SISEVENT.TD_EVENTO (TITULO ASC);

ALTER TABLE SISEVENT.TD_EVENTO
ADD CONSTRAINT TD_EVENTO_PK PRIMARY KEY 
(
  IDEVENT 
)
ENABLE;

CREATE INDEX TD_FERIADOS_IDXEST ON SISEVENT.TD_FERIADOS (ESTADO ASC);

CREATE INDEX TD_FERIADOS_IDXFECHAFE ON SISEVENT.TD_FERIADOS (TRUNC(FECHA_FERIADO) ASC);

ALTER TABLE SISEVENT.TD_FERIADOS
ADD CONSTRAINT TD_FERIADOS_PK PRIMARY KEY 
(
  IDFERIADO 
)
ENABLE;

CREATE INDEX TD_FLUJO_IDXEST ON SISEVENT.TD_FLUJO (ESTADO ASC);

CREATE INDEX TD_FLUJO_IDXEVENT ON SISEVENT.TD_FLUJO (IDEVENT ASC);

CREATE INDEX TD_FLUJO_IDXFLUJOPADRE ON SISEVENT.TD_FLUJO (IDFLUJOPADRE ASC);

CREATE INDEX TD_FLUJO_IDXIDTAREAS ON SISEVENT.TD_FLUJO (IDTAREAS ASC);

CREATE INDEX TD_FLUJO_IDXUNIDADDERIVA ON SISEVENT.TD_FLUJO (IDUNIDAD_DERIVA ASC);

CREATE INDEX TD_FLUJO_IDXUNIDADDESTINO ON SISEVENT.TD_FLUJO (IDUNIDAD_DESTINO ASC);

CREATE INDEX TD_FLUJO_IDXUNIDADUSERDESTINO ON SISEVENT.TD_FLUJO (IDUSER_DESTINO ASC);

CREATE INDEX TD_FLUJO_IDXUSERDERIVA ON SISEVENT.TD_FLUJO (IDUSER_DERIVA ASC);

ALTER TABLE SISEVENT.TD_FLUJO
ADD CONSTRAINT TD_FLUJO_PK PRIMARY KEY 
(
  IDFLUJO 
)
ENABLE;

CREATE INDEX TD_GRUPOS_IDXEST ON SISEVENT.TD_GRUPOS (ESTADO ASC);

ALTER TABLE SISEVENT.TD_GRUPOS
ADD CONSTRAINT TD_GRUPOS_PK PRIMARY KEY 
(
  IDGRUPO 
)
ENABLE;


CREATE INDEX TD_GRUPOSFLUJOS_IDXEST ON SISEVENT.TD_GRUPOSFLUJOS (ESTADO ASC);

CREATE INDEX TD_GRUPOSFLUJOS_IDXGRUPO ON SISEVENT.TD_GRUPOSFLUJOS (IDGRUPO ASC);

ALTER TABLE SISEVENT.TD_GRUPOSFLUJOS
ADD CONSTRAINT TD_GRUPOSFLUJOS_PK PRIMARY KEY 
(
  IDGRUPOSFLUJOS 
)
ENABLE;

CREATE INDEX TD_ITINERARIO_IDXDEST ON SISEVENT.TD_ITINERARIO (ORIGENDESTINO ASC);

CREATE INDEX TD_ITINERARIO_IDXDPTO ON SISEVENT.TD_ITINERARIO (CODDPTO ASC);

CREATE INDEX TD_ITINERARIO_IDXEST ON SISEVENT.TD_ITINERARIO (ESTADO ASC);

CREATE INDEX TD_ITINERARIO_IDXEVENT ON SISEVENT.TD_ITINERARIO (IDEVENT ASC);

CREATE INDEX TD_ITINERARIO_IDXFECHAFIN ON SISEVENT.TD_ITINERARIO (TRUNC(FECHA_LLEG_FIN) ASC);

CREATE INDEX TD_ITINERARIO_IDXFECHINI ON SISEVENT.TD_ITINERARIO (TRUNC(FECHA_SALI_INI) ASC);

CREATE INDEX TD_ITINERARIO_IDXPAIS ON SISEVENT.TD_ITINERARIO (CODPAIS ASC);

CREATE INDEX TD_ITINERARIO_IDXPROV ON SISEVENT.TD_ITINERARIO (CODPROV ASC);

ALTER TABLE SISEVENT.TD_ITINERARIO
ADD CONSTRAINT TD_ITINERARIO_PK PRIMARY KEY 
(
  IDITINERARIO 
)
ENABLE;

CREATE INDEX TD_PARTICIPANTES_IDXEST ON SISEVENT.TD_PARTICIPANTES (ESTADO ASC);

CREATE INDEX TD_PARTICIPANTES_IDXFLAGACOMP ON SISEVENT.TD_PARTICIPANTES (FLAGACOMPANIANTE ASC);

CREATE INDEX TD_PARTICIPANTES_IDXTIPO ON SISEVENT.TD_PARTICIPANTES (TIPO ASC);

ALTER TABLE SISEVENT.TD_PARTICIPANTES
ADD CONSTRAINT TD_PARTICIPANTES_PK PRIMARY KEY 
(
  IDPARTICIPANTES 
)
ENABLE;

CREATE INDEX TD_UBICACIONES_IDXDIST ON SISEVENT.TD_UBICACIONES (CODDIST ASC);

CREATE INDEX TD_UBICACIONES_IDXDPTO ON SISEVENT.TD_UBICACIONES (CODDPTO ASC);

CREATE INDEX TD_UBICACIONES_IDXEST ON SISEVENT.TD_UBICACIONES (UBICACION);

CREATE INDEX TD_UBICACIONES_IDXEVENT ON SISEVENT.TD_UBICACIONES (IDEVENT ASC);

CREATE INDEX TD_UBICACIONES_IDXPAIS ON SISEVENT.TD_UBICACIONES (CODPAIS ASC);

CREATE INDEX TD_UBICACIONES_IDXPROV ON SISEVENT.TD_UBICACIONES (CODPROV ASC);


ALTER TABLE SISEVENT.TD_UBICACIONES
ADD CONSTRAINT TD_UBICACIONES_PK PRIMARY KEY 
(
  IDUBICACIONES 
)
ENABLE;


ALTER TABLE SISEVENT.MS_ACTIVIDADES
ADD CONSTRAINT MS_ACTIVIDADES_FK1 FOREIGN KEY
(
  IDUSER_CREA 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;

ALTER TABLE SISEVENT.MS_ACTIVIDADES
ADD CONSTRAINT MS_ACTIVIDADES_FK2 FOREIGN KEY
(
  IDUSER_MODIF 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;
ALTER TABLE SISEVENT.MS_CATEGORIAS
ADD CONSTRAINT MS_CATEGORIAS_FK1 FOREIGN KEY
(
  IDUSER_CREA 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;

ALTER TABLE SISEVENT.MS_CATEGORIAS
ADD CONSTRAINT MS_CATEGORIAS_FK2 FOREIGN KEY
(
  IDUSER_MODIF 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;
ALTER TABLE SISEVENT.MS_INSTITUCIONES
ADD CONSTRAINT MS_INSTITUCIONES_FK1 FOREIGN KEY
(
  IDUSER_CREA 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;

ALTER TABLE SISEVENT.MS_INSTITUCIONES
ADD CONSTRAINT MS_INSTITUCIONES_FK2 FOREIGN KEY
(
  IDUSER_MODIF 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;
ALTER TABLE SISEVENT.MS_PAISES
ADD CONSTRAINT MS_PAISES_FK1 FOREIGN KEY
(
  IDUSER_CREA 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;

ALTER TABLE SISEVENT.MS_PAISES
ADD CONSTRAINT MS_PAISES_FK2 FOREIGN KEY
(
  IDUSER_MODIF 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;
ALTER TABLE SISEVENT.MS_PERSONAS
ADD CONSTRAINT MS_PERSONAS_FK1 FOREIGN KEY
(
  IDUSER_CREA 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;

ALTER TABLE SISEVENT.MS_PERSONAS
ADD CONSTRAINT MS_PERSONAS_FK2 FOREIGN KEY
(
  IDUSER_MODIF 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;
ALTER TABLE SISEVENT.MS_ROLES
ADD CONSTRAINT MS_ROLES_FK1 FOREIGN KEY
(
  IDUSER_CREA 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;

ALTER TABLE SISEVENT.MS_ROLES
ADD CONSTRAINT MS_ROLES_FK2 FOREIGN KEY
(
  IDUSER_MODIF 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;
ALTER TABLE SISEVENT.MS_TAREAS
ADD CONSTRAINT MS_TAREAS_FK1 FOREIGN KEY
(
  IDUSER_CREA 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;

ALTER TABLE SISEVENT.MS_TAREAS
ADD CONSTRAINT MS_TAREAS_FK2 FOREIGN KEY
(
  IDUSER_MODIF 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;
ALTER TABLE SISEVENT.MS_UBIGEO
ADD CONSTRAINT MS_UBIGEO_FK1 FOREIGN KEY
(
  IDUSER_CREA 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;

ALTER TABLE SISEVENT.MS_UBIGEO
ADD CONSTRAINT MS_UBIGEO_FK2 FOREIGN KEY
(
  IDUSER_MODIF 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;
ALTER TABLE SISEVENT.MS_UNIDADES_ORG
ADD CONSTRAINT MS_UNIDADES_ORG_FK1 FOREIGN KEY
(
  IDUSER_CREA 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;

ALTER TABLE SISEVENT.MS_UNIDADES_ORG
ADD CONSTRAINT MS_UNIDADES_ORG_FK2 FOREIGN KEY
(
  IDUSER_MODIF 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;
ALTER TABLE SISEVENT.PRT_PARAMETROS
ADD CONSTRAINT PRT_PARAMETROS_FK1 FOREIGN KEY
(
  IDUSER_CREA 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;

ALTER TABLE SISEVENT.PRT_PARAMETROS
ADD CONSTRAINT PRT_PARAMETROS_FK2 FOREIGN KEY
(
  IDUSER_MODIF 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;
ALTER TABLE SISEVENT.TD_ANEXOS
ADD CONSTRAINT TD_ANEXOS_FK1 FOREIGN KEY
(
  IDUSER_CREA 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;

ALTER TABLE SISEVENT.TD_ANEXOS
ADD CONSTRAINT TD_ANEXOS_FK2 FOREIGN KEY
(
  IDUSER_MODIF 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;
ALTER TABLE SISEVENT.TD_EVENTO
ADD CONSTRAINT TD_EVENTO_FK1 FOREIGN KEY
(
  IDUSER_CREA 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;

ALTER TABLE SISEVENT.TD_EVENTO
ADD CONSTRAINT TD_EVENTO_FK2 FOREIGN KEY
(
  IDUSER_MODIF 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;
ALTER TABLE SISEVENT.TD_FLUJO
ADD CONSTRAINT TD_FLUJO_FK1 FOREIGN KEY
(
  IDUSER_CREA 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;

ALTER TABLE SISEVENT.TD_FLUJO
ADD CONSTRAINT TD_FLUJO_FK2 FOREIGN KEY
(
  IDUSER_MODIF 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;
ALTER TABLE SISEVENT.TD_GRUPOS
ADD CONSTRAINT TD_GRUPOS_FK1 FOREIGN KEY
(
  IDUSER_CREA 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;

ALTER TABLE SISEVENT.TD_GRUPOS
ADD CONSTRAINT TD_GRUPOS_FK2 FOREIGN KEY
(
  IDUSER_MODIF 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;
ALTER TABLE SISEVENT.TD_GRUPOSFLUJOS
ADD CONSTRAINT TD_GRUPOSFLUJOS_FK1 FOREIGN KEY
(
  IDUSER_CREA 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;

ALTER TABLE SISEVENT.TD_GRUPOSFLUJOS
ADD CONSTRAINT TD_GRUPOSFLUJOS_FK2 FOREIGN KEY
(
  IDUSER_MODIF 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;
ALTER TABLE SISEVENT.TD_ITINERARIO
ADD CONSTRAINT TD_ITINERARIO_FK1 FOREIGN KEY
(
  IDUSER_CREA 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;

ALTER TABLE SISEVENT.TD_ITINERARIO
ADD CONSTRAINT TD_ITINERARIO_FK2 FOREIGN KEY
(
  IDUSER_MODIF 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;
ALTER TABLE SISEVENT.TD_PARTICIPANTES
ADD CONSTRAINT TD_PARTICIPANTES_FK1 FOREIGN KEY
(
  IDUSER_CREA 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;

ALTER TABLE SISEVENT.TD_PARTICIPANTES
ADD CONSTRAINT TD_PARTICIPANTES_FK2 FOREIGN KEY
(
  IDUSER_MODIF 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;
ALTER TABLE SISEVENT.TD_UBICACIONES
ADD CONSTRAINT TD_UBICACIONES_FK1 FOREIGN KEY
(
  IDUSER_CREA 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;

ALTER TABLE SISEVENT.TD_UBICACIONES
ADD CONSTRAINT TD_UBICACIONES_FK2 FOREIGN KEY
(
  IDUSER_MODIF 
)
REFERENCES MS_USUARIOS
(
  IDUSUARIO 
)
ENABLE;

ALTER TABLE SISEVENT.MS_USUARIOS
ADD CONSTRAINT MS_USUARIOS_UK1 UNIQUE 
(
  USERNAME 
)
USING INDEX SISEVENT.MS_USUARIOS_IDXUSERNAME
ENABLE;

CREATE SEQUENCE SISEVENT.SQ_MS_ACTIVIDADES INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SISEVENT.SQ_MS_CATEGORIAS INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SISEVENT.SQ_MS_INSTITUCIONES INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SISEVENT.SQ_MS_PAISES INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SISEVENT.SQ_MS_PERSONAS INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SISEVENT.SQ_MS_ROLES INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SISEVENT.SQ_MS_TAREAS INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SISEVENT.SQ_MS_UBIGEO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SISEVENT.SQ_MS_UNIDADES_ORG INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SISEVENT.SQ_PRT_PARAMETROS INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SISEVENT.SQ_TD_ANEXOS INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SISEVENT.SQ_TD_EVENTO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SISEVENT.SQ_TD_FLUJO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SISEVENT.SQ_TD_GRUPOS INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SISEVENT.SQ_TD_GRUPOSFLUJOS INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SISEVENT.SQ_TD_ITINERARIO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SISEVENT.SQ_TD_PARTICIPANTES INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SISEVENT.SQ_TD_UBICACIONES INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SISEVENT.SQ_MS_USUARIOS INCREMENT BY 1 START WITH 1;

